-- Step 1: Business Table Inserts (Address Only) --
-- Make sure 'Zip_Code' is the correct zip column name in your 'business' table! --
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('1489 Watermelon Dr', 'Lincoln', 'Nebraska', '78593');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('6484 Nectarine Ter', 'Austin', 'Texas', '22557');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('130 Mulberry Ln', 'Olympia', 'Washington', '41862');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('2249 Lemon Pl', 'Boise', 'Idaho', '56578');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4799 Blackberry St', 'Jefferson City', 'Missouri', '50442');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('5110 Grapefruit Ter', 'Annapolis', 'Maryland', '78429');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('7179 Banana Ter', 'Nashville', 'Tennessee', '78923');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('5582 Plantain Ct', 'Hartford', 'Connecticut', '14217');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9346 Quince St', 'Bismarck', 'North Dakota', '26304');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9270 Banana Ave', 'Dover', 'Delaware', '99228');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('6381 Pear Rd', 'Carson City', 'Nevada', '41893');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('413 Quince Blvd', 'Little Rock', 'Arkansas', '54796');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('3475 Boysenberry Pl', 'Madison', 'Wisconsin', '04373');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9067 Blueberry Blvd', 'Santa Fe', 'New Mexico', '60370');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4729 Watermelon Way', 'Columbia', 'South Carolina', '66219');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('3378 Tangerine Ct', 'Springfield', 'Illinois', '58705');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('6488 Grape Ter', 'Oklahoma City', 'Oklahoma', '13756');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8858 Cantaloupe Blvd', 'Jefferson City', 'Missouri', '08759');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9583 Kumquat Way', 'Pierre', 'South Dakota', '58816');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('73 Kumquat Ln', 'Indianapolis', 'Indiana', '01004');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8247 Olive Way', 'Baton Rouge', 'Louisiana', '54861');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('5131 Lemon Dr', 'Little Rock', 'Arkansas', '79265');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8988 Salmonberry Way', 'Boise', 'Idaho', '66169');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('5444 Yuzu Dr', 'Madison', 'Wisconsin', '52338');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('1688 Starfruit Ln', 'Frankfort', 'Kentucky', '85083');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('586 Apricot Pl', 'Denver', 'Colorado', '22366');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4827 Apple Way', 'Oklahoma City', 'Oklahoma', '51899');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('2971 Raspberry Ln', 'Sacramento', 'California', '66261');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('706 Banana Blvd', 'Concord', 'New Hampshire', '89709');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('3757 Cranberry Pl', 'Pierre', 'South Dakota', '12612');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8340 Tamarind Way', 'Annapolis', 'Maryland', '64961');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4502 Tangerine Way', 'Saint Paul', 'Minnesota', '71586');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('6093 Kiwifruit Way', 'Augusta', 'Maine', '81818');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('1416 Dragonfruit Way', 'Boston', 'Massachusetts', '77518');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8220 Cantaloupe St', 'Augusta', 'Maine', '79655');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8229 Avocado Ave', 'Jackson', 'Mississippi', '29346');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('387 Banana Blvd', 'Cheyenne', 'Wyoming', '53481');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4115 Dragonfruit Ave', 'Austin', 'Texas', '47921');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4353 Boysenberry Rd', 'Harrisburg', 'Pennsylvania', '97925');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('4018 Quince Dr', 'Santa Fe', 'New Mexico', '97655');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9879 Pear Ave', 'Columbia', 'South Carolina', '17847');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('1346 Grape Ln', 'Montgomery', 'Alabama', '63900');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('6706 Blackberry St', 'Columbus', 'Ohio', '41264');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9949 Kiwifruit Dr', 'Phoenix', 'Arizona', '37752');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('1206 Durian Ln', 'Montpelier', 'Vermont', '21998');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('2575 Jackfruit Ct', 'Frankfort', 'Kentucky', '68943');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('3910 Melon Dr', 'Annapolis', 'Maryland', '90942');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('6164 Starfruit Ct', 'Sacramento', 'California', '85202');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('9134 Satsuma Dr', 'Trenton', 'New Jersey', '39760');
INSERT INTO business (Street, City, State, Zip_Code) VALUES ('8487 Mango Pl', 'Oklahoma City', 'Oklahoma', '54764');

-- Step 2: regorkstore Table Inserts (References Business) --
INSERT INTO regorkstore (Business_ID) VALUES (36);
INSERT INTO regorkstore (Business_ID) VALUES (48);
INSERT INTO regorkstore (Business_ID) VALUES (9);
INSERT INTO regorkstore (Business_ID) VALUES (18);
INSERT INTO regorkstore (Business_ID) VALUES (39);
INSERT INTO regorkstore (Business_ID) VALUES (40);
INSERT INTO regorkstore (Business_ID) VALUES (14);
INSERT INTO regorkstore (Business_ID) VALUES (11);
INSERT INTO regorkstore (Business_ID) VALUES (13);
INSERT INTO regorkstore (Business_ID) VALUES (24);
INSERT INTO regorkstore (Business_ID) VALUES (44);
INSERT INTO regorkstore (Business_ID) VALUES (4);
INSERT INTO regorkstore (Business_ID) VALUES (19);
INSERT INTO regorkstore (Business_ID) VALUES (45);
INSERT INTO regorkstore (Business_ID) VALUES (16);
INSERT INTO regorkstore (Business_ID) VALUES (34);
INSERT INTO regorkstore (Business_ID) VALUES (7);
INSERT INTO regorkstore (Business_ID) VALUES (10);
INSERT INTO regorkstore (Business_ID) VALUES (26);
INSERT INTO regorkstore (Business_ID) VALUES (23);
INSERT INTO regorkstore (Business_ID) VALUES (46);
INSERT INTO regorkstore (Business_ID) VALUES (3);
INSERT INTO regorkstore (Business_ID) VALUES (43);
INSERT INTO regorkstore (Business_ID) VALUES (33);
INSERT INTO regorkstore (Business_ID) VALUES (30);
INSERT INTO regorkstore (Business_ID) VALUES (35);
INSERT INTO regorkstore (Business_ID) VALUES (42);
INSERT INTO regorkstore (Business_ID) VALUES (1);
INSERT INTO regorkstore (Business_ID) VALUES (38);
INSERT INTO regorkstore (Business_ID) VALUES (37);
INSERT INTO regorkstore (Business_ID) VALUES (50);
INSERT INTO regorkstore (Business_ID) VALUES (49);
INSERT INTO regorkstore (Business_ID) VALUES (31);
INSERT INTO regorkstore (Business_ID) VALUES (41);
INSERT INTO regorkstore (Business_ID) VALUES (22);
INSERT INTO regorkstore (Business_ID) VALUES (27);
INSERT INTO regorkstore (Business_ID) VALUES (29);
INSERT INTO regorkstore (Business_ID) VALUES (6);
INSERT INTO regorkstore (Business_ID) VALUES (32);
INSERT INTO regorkstore (Business_ID) VALUES (8);

-- Step 3: Supplier Table Inserts (References Business, has Name) --
INSERT INTO supplier (Business_ID, Name) VALUES (2, 'Ocsys Corp');
INSERT INTO supplier (Business_ID, Name) VALUES (5, 'SU Doofs');
INSERT INTO supplier (Business_ID, Name) VALUES (12, 'GFP Group');
INSERT INTO supplier (Business_ID, Name) VALUES (15, 'Ramsey Food Service');
INSERT INTO supplier (Business_ID, Name) VALUES (17, 'TH Hack Co.');
INSERT INTO supplier (Business_ID, Name) VALUES (20, 'Ehek Distributions');
INSERT INTO supplier (Business_ID, Name) VALUES (21, 'Seyer Holdings');
INSERT INTO supplier (Business_ID, Name) VALUES (25, 'Keith Lee Foods');
INSERT INTO supplier (Business_ID, Name) VALUES (28, 'Crockpot Foods');
INSERT INTO supplier (Business_ID, Name) VALUES (47, 'IFNU Inc.');



commit;
