-- PRODUCT Table Inserts (including Generic Water) --
delete from product;
delete from needsComponent;

ALTER TABLE product
MODIFY (Product_ID GENERATED ALWAYS AS IDENTITY (START WITH 1));

INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Health & Nutrition Drink - Classic Malt', 'Horlicks', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Turmeric Latte - Golden Milk/Haldi Doodh', 'Nutty Yogi', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Tulsi Ginger Tea', '24 Mantra', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Drink - Mango, Fresh ''N'' Juicy', 'Frooti', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organics Premium Green Tea', '18 Herbs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mineral Water', 'Bisleri ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chocolate Health Drink - Bournvita', 'Bournvita', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cold Extracted Juice - Basics, Aloe Vera Lemonade', 'Raw Pressery', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('This Mocha  3 In 1 Premix Instant Coffee', 'Continental', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fizz Classic Cola - Guilt-Free Soft Drink With Zero Sugar & No Preservatives', 'Shunya', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Green Tea - Chamomile Lavender Long Leaf', 'VAHDAM', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Nilgiri Green Tea Bags - Taizen Cinnamon', 'Teamonk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sharbat - Paan, Syrup', 'Gulabs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chocolate Shake With Real Belgian Chocolate', 'Sunfeast', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Deccan Gold - Organic Filter Coffee', 'PRISTINE', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sharbat - Jeera, Syrup', 'Gulabs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hot Chocolate Drink Powder Mix', 'Cadbury', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tea - Fresh Lemon', 'Taj Mahal', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Strong Filter Coffee', 'iD', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Darjeeling Tea - Long Leaf', 'Lipton ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ayurvedic Tea', 'Namhya', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coffee - Classic', 'Nescafe ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bold Berries Smoothie - 100% Natural, No Added Sugar', 'Smoodies', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Margarita - Lemon & Lime', '&Stirred', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Leaf Tea - Chikamagalur Aroma, Premium, Fresh', 'Riseup', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Herbal Tea - Indian, Whole Leaf', 'Octavius', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soft Drink - Lemon', '7 Up', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Darjeeling Tea', 'Lipton ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ayurvedic Tea Masala - 21 Active Ingredients', 'Kapiva Ayurveda', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tulsi  Green Tea - Classic', 'ORGANIC INDIA', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Deccan Gold - Premium Dust Tea', 'PRISTINE', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Protein Plus, Vanilla', 'Horlicks', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chakra Gold Elaichi Tea', 'Tata Tea', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Non-Alcoholic Beer Can - Beverage, Malt Flavour', 'Barbican ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Glucose Based Beverage Mix - Mango', 'Glucon-D', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Thandai', 'Gulabs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tea', 'Red Label', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soft Drink 2.25L+Mango Drink 600ml', 'bb Combo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Filter Coffee Decoction', 'sumeru', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Earl Grey Citrus Long Leaf Black Tea', 'VAHDAM', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Juice - Mango Magic', 'B Natural', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chilli Guava Smoothie - 100% Natural, No Added Sugar', 'Smoodies', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Assam Exotic Long Leaf Black Tea - Pyramid Bags', 'VAHDAM', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Glucose D', 'Moti''s', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Women''s Plus Caramel', 'Horlicks', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soft Drink 2.25L+Mango Drink 600ml', 'bb Combo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Native Haat - Badam Vita', 'Rasna', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Classic Instant Coffee', 'Nescafe ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Spiced Tea - Blend Of 7 Refreshing Spices', 'Wagh Bakri', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lime Juice Cordial', 'Morton', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Door/Floor Mat - Multi Surplus', 'SHAMROCK', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tissue Paper Roll - 2 Ply, Toilet', 'Mystique', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fabric Cleaner - Cuffs & Collars Cleans (liquid fabric whitener)', 'Robin', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Aries Plastic Basket 333', 'Nakoda', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Plastic Basket Fruit & Vegetable Colander/Strainer - Small, Yellow, Deluxe, 13220PB', 'Ratan', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('100% Compostable & Bio-Degradable Garbage Bags - Small, 17X19', 'Pearl Luxury', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Golu Patla Plastic Stool - Assorted Colour', 'Polyset', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Metro Mug - Plain, Assorted', 'JOYO', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Toilet Roll - 8 Rolls, 3 ply', 'Paseo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fabric Conditioner - Geranium & Lavender', 'PureCult', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Colour Catcher Sheets', 'Dylon ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Swift Plastic Hanger / Cloth Hanger', 'Mr. Boss', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cloth Clip', 'Spark', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Express Bathroom', 'Smac', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cleaning Duster - With PP Bristles, Bendable', 'Liao', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Detergent Bar - Stain Care', 'Henko', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Multipurpose Cotton Leafy Printed Regular Grocery Bag', 'Clean Planet', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Magic Mop - Heavy Duty PVA Expandable With Steel Stick', 'Liao', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Kitchen Cleaner - Powers Through Grease & Grime', 'Mr Muscle', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Kitchen Moppy', 'Magix', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Disinfectant Skin & Surface Wipes, Original 40 Count + Menthol Cool, 500 ml', 'Dettol', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dishwash - Kraft', 'Pril', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Phenyle - Black Disinfectant Fluid', 'Germisol', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Complete Detergent Washing Powder', 'Ariel ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Disney Fish Frenzy - Finding Dory Card Game for Kids, Multicolour, Gift', 'Kaadoo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ruler - Stainless Steel', 'Darshi', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Plastic Dustbin/Basket - Pink,  PK BB 619 3', 'Sunty', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Notebook - A4, Unruled, 140 Pages', 'Classmate', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Swachh Plastic Pedal Dust & Garbage Bin - Assorted Colour', 'Nakoda', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Plastic Tub - Assorted Colour, Modern', 'Nakoda', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Germ Protection Fruit & Veggie Wash – Natural Ingredient Based, Removes Germs, Bacteria, Fungus, Wax & Dirt', 'Godrej Protekt', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Notebook - Unruled, Long', 'Classmate', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Home Kit Box Blister', 'Pidilite', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Glue Board To Trap Rats - Big', 'M Stick', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Freshener - Urinal & Toilet', 'Hi-Fresh', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Disinfecting Wipes - Fresh Scent', 'Clorox', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mop Refil Thread', 'Polyguards', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Facial Tissues Box - 2 Ply - 100% virgin pulp/paper', 'BB Home', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dishwash Bar 200 gm + Dishwash Gel - Lemon 250 ml', 'Vim', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Long Notebook-Unruled+Ruled, Single Line (172Pages)+Single Line, Ruled 160Pages', 'Classmate', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Stapler HP-10', 'Kangaroo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Advanced Detergent Powder', 'Rin', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Notebook - Ruled, Small, Single Line, Soft Bound', 'Classmate', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Matic Top Load Detergent Powder', 'Surf Excel', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cleaner - Fabric', 'Scotchgard', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Refillable Permanent Marker Pen', 'Luxor', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Printed Fabric Pencil Pouch - Purple, BB1263DPPL', 'DP', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Active - Detergent Cake Blue', 'Wheel ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mr. Clean Dust Pan & Bin - Big', 'Nakoda', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Combs Derby Deluxe', 'Ego of Paris', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mutton - Boneless, 2-3 pcs, Antibiotic Residue-Free, Growth Hormone-Free', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sardine In Soy Sauce', 'Golden Prize', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Eggs - Country Duck', 'Mpm', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mutton - Liver, Antibiotic Residue-Free, Growth Hormone-Free', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Pork', 'Quickee''S', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Cheese & Onion Sausage', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bombay Duck', 'H.S. Dry Fish', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Catch Breaded Fish Fillets', 'Ifb', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Spicy Breast Strips', 'Meatzza', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Catch Prawns - Jumbo', 'Ifb', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Nathili', 'H.S. Dry Fish', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mackerel Fish - Medium Whole Cleaned, Preservative Free', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pearl Spot Fish - Medium, Whole, Preservative Free, 3-4 pcs', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Catch Basa Fish Fillets', 'Ifb', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Salami - Chicken N Cheese, Spicy', 'Zorabian', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Korai Fish', 'H.S. Dry Fish', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Boneless Chicken Thighs', 'Meatzza', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rohu Fish (Large) - Curry Cut/Bengali Cut 1 kg + Mutton - Curry Cut 1 kg', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pork - Mortadella with Pistachios, P.G.I, Sliced', 'Fresho Signature', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ham - Premium Beechwood Bacon, Smoked', 'La Carne', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Pork, Cocktail', 'Quickee''S', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Seer Fish', 'H.S. Dry Fish', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Pork, Super Bacon', 'Quickee''S', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Pork', 'Quickee''S', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Frozen Prawns - Medium', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Chicken', 'Tannys', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken - Momos, Spicy', 'Prasuma', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresho Farm Eggs  Medium 30 pcs + Kara Coconut Milk UHT Classic, Imported 200 ml', 'bb Combo', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Chicken with Chives', 'Bon Appetit', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pork - Fresh Bacon, Sliced', 'Fresho Signature', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Boneless Chicken Breast', 'Meatzza', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Canned Skipjack Light Meat Tuna - Chunk In Olive Oil', 'Golden Prize', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ham - Chicken Chilli, Breast', 'La Carne', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mutton Curry Cuts', 'Premier', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pork Cocktail Sausage', 'La Carne', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Catch Fish Fingers', 'Ifb', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Prawns Hariyali Masala', 'Gadre', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken - Seek Kabab', 'Meatzza', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Clam   400 GRM', 'Tasty Nibbles', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Eggs - Brown, Antibiotic Free', 'Just Laid', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken - Cheese & Onion Sausages', 'Tannys', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Burger Patty - Chicken', 'Republic of Chicken', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ham - Chicken Pariser, Smoked', 'La Carne', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Catla Fish - Large, Steak/Slice, Preservative Free, 12-14 pcs', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Fries', 'Meatzza', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Bell Pepper Salami', 'La Carne', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sausage - Chicken Piri Piri', 'La Carne', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Frankfurter - Chicken', 'Quickee''S', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pork - Prosciutto Cotto Ham, Sliced', 'Fresho Signature', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Shami Kabab', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dry Chutney Powder - Garlic Chutney', 'Just A Minute', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Red Raw Rice/Akki', 'bb Popular', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Seeds - Amaranth(Rajgeera)', 'Organic Tattva', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Carom Seeds/Ajwain/Om Kalu', 'Earthon', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rajwadi Tea (Chai) Masala - Immunity Booster', 'Jawai', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coconad - Coconut Oil', 'Klf ', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gulkand - Premium With Dry Fruits', 'Future Organics', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic - Poha 1 kg + Organic - Raw Peanuts 500 gm', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Himalayan Pink Salt/Uppu Granules', 'Natural Tattva ', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Noodle Masala', 'Keya', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('bb Royal Thin Poha 1Kg + Besan Flour + Ordinary Sooji (Each 1kg)', 'bb Combo', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Dosa Rice', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Powder - Dry Mango', 'Badshah', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Green Moong//Hesaru Kaalu - Split', 'Super Saver', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Black Salt/Kala Namak - Whole', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hommade - Ginger Garlic Paste', 'Dabur', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gojju Magic Masala Powder', 'MTR', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chatpata Chat Masala', 'Catch', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Certified Organic Mustard Oil', 'Nutriorg', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Powder Masala - Vangi Bhath', 'Ogara', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Black Pepper/Kari Menasui', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ragi Flour/Ragi Hittu', 'Organic Tattva', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Jaggery/Bella Powder', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Powder - Coriander', 'Pro Nature', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Peru Vati', 'Chandan', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic - Black Cardamom Ealachi, Whole', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Basmati Rice/Basmati Akki - Sehat Mini Mogra', 'Daawat ', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sonamasuri Hand Pounded', 'Organic Tattva', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Powder - Coriander', 'Aashirvaad', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sampoorna Chakki Atta/Godihittu', 'Nature Fresh', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Majestic Rose Mouth Freshener', 'Chandan', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Seeds - Sunflower', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mother''s Recipe mix-paneer-butter-masala 75 g Pouch', 'Mother''s Recipe', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Masala - Fish', 'Badshah', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dried Blueberries', 'FabBox', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Basmati Rice/Basmati Akki - Super', 'India Gate', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chhole Masala', 'Catch', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ponni Raw Rice/Akki - Super Premium', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Toor Dal/Togari Bele', '24 Mantra', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Refined - Sunflower Oil', 'Dhara ', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Thyme - Pesticide Free', 'Safe Harvest', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cow Ghee/Tuppa - A2 Badri', 'Himalayan Natives', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic - Idly/Idli Rice/Akki', 'bb Royal', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Puttupodi - White', 'Double Horse', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Salt/Uppu', 'Saffola', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ragi Flour/Ragi Hittu', 'Manna ', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rajwadi Kesari Milk Masala', 'Jawai', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chana Sattu Refreshing Drink Powder', 'Manna ', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Amchur Powder 100g + Sambhar Masala 100 g', 'Catch', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Wheat Daliya', 'MeraKisan', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pomegranate - Peeled', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Neem Giloy (Amruta Balli) - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('White Orchids', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Capsicum - Diced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Watermelon  - Small', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Sprouts Mixed Gram', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pumpkin - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Watermelon - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pineapple - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sambhar Onion (Small Onion)', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Beans - Diced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Boiled Sweet Corn Kernel - Spice Up With Cheese And Herbs Seasoning', 'Tadaa', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Brinjal - Varikatri, Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Baby Corn - Peeled', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pineapple', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coconut - Medium', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Asparagus', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pomegranate - Premium', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coconut - Diced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Broccoli - Florets', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ladies Finger - Diced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lemon Grass', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Carrots Sliced, Broccoli Florets and Cauliflower Florets', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mosambi - Economy', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Potato - Wedges', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Brinjal - Green, Long', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Beetroot - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Palak - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Avocado', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sweet Corn', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Papaya - Raw', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ladies Finger', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Yellow Pumpkin - Avial Cut', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coconut - Diced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Apple - Red Delicious, Economy', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pomegranate', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Beans - French, Ring', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bottle Gourd', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Capsicum - Red', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Beans - Cluster, Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Apricot - Dried', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cut - Fruit Salad', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lettuce - Iceberg', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Watermelon - Organically Grown', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sugarcane - Diced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Asparagus', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coccinia - Sliced', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Garlic - Peeled', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chrysanthemum/Shevanti Flower', 'RoseBazaar', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ooty Potato - Medium', 'Fresho', 'Commodity', 'kg');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Carbon Zinc Battery Red AA 1015', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lithium Battery Ultimate AAA', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Led Batten - 20W CDL Dazzle Ray, Cool Day Light White', 'Crompton', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Safelite LED Bulb - 0.5 Watt, White, Cool Day, B22', 'Wipro', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 0.5-Watt, Orange, Deco Mini Base B22', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 12-Watt, Base B22 (SSK-SRL-12W)', 'Syska', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Deco Mini Base B22 0.5-Watt LED Bulb - Red', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery Power AA - Long Lasting Power', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Copper String Light 10 M & 100 LED With Adapter For Decoration - Red', 'Lexton', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('USB String Fairy Lights 3M 30 LED For Decoration - Multicolour', 'Mansaa', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery AAA-1B6', 'Panasonic', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 3-Watt, Base B22 1pc + LED Bulb - 5-Watt, Base B22 1pc', 'Syska', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Combo - LED Bulb 9W + 9W', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery AAA-2B', 'Panasonic', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Clippy 2 Pin Extension Box With 10 Meter Wire 1088', 'Milltec', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Divine - Riddhi-Siddhi Glow LED Lamp 1114', 'Milltec', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Carbon Zinc Battery Red HD AAA 1012', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED T-Bulb - 8 Watt, Cool Daylight, B22', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ultra Alkaline Battery AA', 'Duracell', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Smart LED Bulb - 7 Watt, Wi-Fi Enabled, Multicolour (SSK-SMW 7W)', 'Syska', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rechargeable Battery Combo 2 - AA 1000 Series With Charger', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Decorative Party Light Leaves String LED Light 7.5 M - Warm White', 'Lexton', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ultra Alkaline Battery 9V AAA', 'Duracell', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery E96/AAAA', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('USB String Fairy Lights 3M 30 LED Heart Bead Gold Chain For Decoration', 'Mansaa', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Decorative Party Light Big Star String LED Light 2 M - Multicolour', 'Lexton', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Lamp/T-Bulb - 14 Watt, Cool Daylight White, B22 Base', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lithium Battery Ultimate AA', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Clippy 2 Pin Extension Box With 5 Meter Wire 1086', 'Milltec', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 12 Watt, Cool Daylight, B22 Base', 'AGARO', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rechargeable Battery AA 700 Mah With Charger, BP4', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('2 Pin Conversion Plug 1068', 'Milltec', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Batten - 20 Watt, Slimline Next', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED T-Bulb - 18 Watt, Cool Daylight, B22', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery AA Ultima 2115 BP4', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery Max AAA (4+2 Free)', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 14 Watt, Cool Day Light, Base B22D', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rechargeable Battery AA 700 Mah BP2', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Garnet LED Bulb -12 Watt, White, Cool Day, B22', 'Wipro', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Lamp - 20 Watt, Cool Daylight, T-Bulb/Beamer Base B22', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 9-Watt, Base B22 (SSK-SRL-9W)', 'Syska', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Carbon Zinc Battery Red HD AA 1015', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 7-Watt, Base B22 1pc + 9-Watt, Base B22 1pc + 12-Watt, Base B22 1pc', 'Syska', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Clippy 3 Pin Extension Box With 5 Meter Wire 1087', 'Milltec', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery Max AA', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rechargeable Battery AA 2100 mah Ultima', 'Eveready', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Battery AAA Gold 15V 4DG', 'Nippo', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('USB Universal Wall/Travel Charger Adapator - White', 'Milltec', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('LED Bulb - 8.5 Watt, Cool Day Light, Ace Saver Base B22', 'Philips', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Alkaline Battery Max AAA (8+4 Free)', 'Energizer', 'Serialized', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('NHP 8104 Silky Shine Hot & Cold Foldable Hair Dryer - 1400 Watt', 'Nova', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Radiant Pearl Cellular Lightening 1 Facial Kit', 'Lotus Herbals', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sunscreen - For All Skin, SPF 30', 'Organic Harvest', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Shaving Foam Sensitive Type', 'Vi-john', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Skin Therapy Oil - Rosehip', 'Palmer''s', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Body Lotion For Very Dry Skin, Nourishing Body Milk With 2x Almond Oil, For Men & Women', 'Nivea', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Oil Control Face Wash For Oily Skin - 12hr Oil Control With 10x Vitamin C Effect', 'Nivea Men', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Natural Glow Kesar Face Wash', 'Himalaya', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Body Wash - Mint & Cucumber, Shower Creme', 'Vivel', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hand Soap - Lemon Extract', 'Skin Cottage ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Germ Protection Hand Sanitizer', 'Godrej Protekt', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cold Balm', 'Himalaya Wellness', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hajmola Maha Candy - Aam+Imli', 'Dabur', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Multani Mitti Face Pack Powder', 'Banjara''s', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('De-Tan Facewash For Men', 'Beardo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pure Lemon Glycerin Soap - Cold Processed, 100% Natural & Organic', 'Soulflower', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rushikanti Multani Mitti With Aloevera', 'Akshara Herbals', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Herbal Lemon Facial Massage Cream', 'Olivia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('UV Away Moist Jumbo Sun Block', 'It''s Skin', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pre Shave Gel Tube - Ultra Comfort', 'Gillette', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bodyfit Overnight Pads - XXXL', 'Sofy', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Nano Sun Block Sun Protective Cream Spf 60', 'Shahnaz Husain', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Avacado Fairness Facial Sheet Mask EX', 'Mirabelle', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Super Set for Women', 'Playboy', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Now Eau De Toilette', 'Tommy Hilfiger', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Total Effects - SPF 15', 'Olay', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Classic Deodorant Spray for Men', 'Brut', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Opticare Smooth Straight Shampoo', 'Matrix', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soothing Cucumber Facial Scrub With Apricot Seeds', 'TJORI', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Black Naturals Hair Colour Shade 1-Deep Black 20 ml + 20 gm', 'Garnier', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hand Wash', 'PureCult', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Anti-Oxidant 24 Active Oils - Professional Face Oil', 'StBotanica', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Refill Handwash - Herbal', 'Medimix', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rejuvenating Cucumber & Aloe Vera Face Pack For Skin', 'Everyuth Naturals', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Protein Bleach', 'Glamveda', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hair Vital Bioactive Oil With Olive, Castor, Almond, Jojoba, Rosemary, Tea Tree', 'StBotanica', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sun Protect Non-Oily Sunscreen SPF 50', 'Ponds', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Loofah/Sponge Scrubber/Body Bath - Dual Side, Hangable, Blue, BH-070', 'BB Home', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Celeste & Sheer Perfume For Women', 'Skinn by Titan', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Safe Sun Uv Screen Matte Gel PA+++ - SPF 50', 'Lotus Herbals', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Essential Oil - Palmarosa', 'Aroma Magic ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Urban Musk Eau De Toilette Deodorant - For Man', 'Nike', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('L''amant - Eau De Toilette, For Her', 'Engage', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Skin Fruits Brightening Lemon Face Wash', 'Joy', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fresh Spicy', 'Fogg ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Deodorant Spray - Original', 'Lomani', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Whitening Talc Touch Deodorant', 'Nivea', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Natural Age Control Day Cream', 'The Moms Co', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bathing Soap', 'Mysore Sandal', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Wheat Grass Dietary Supplement', 'Healthmeds', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Probiotic Health Drink - Light', 'Yakult', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soya Milk - Vanilla', 'Sofit ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cholesterol Free - Spread', 'Delicious', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Unsalted Butter', 'Happy Milk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cheddar Cheese Spread - Pepper', 'Nandini', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pizza Rusk', 'Elite', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Real Ice Cream - Butterscotch Bliss', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Almond Roasted', 'Lovely Bake Studio', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Processed Cheese - Chiplets Cubes', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Almond Roasted', 'Lovely Bake Studio', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Protein Milkshake - Banana & Honey', 'Raw Pressery', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fruit Yoghurt - Blueberry', 'Milky Mist', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ginger Milk', 'Heritage', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Milk Bread - Safe, Preservative Free', 'Fresho', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Centre Filled Chocolate Cake - with Vanilla Cream', 'Winkies', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soya Milk - Vanilla', 'Sofit ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Butterscotch Gold Ice Cream', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gobbles Butter Blast Cake', 'Britannia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Britannia Pav', 'Britannia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sterilised Double Toned Flavored Milk - Pista', 'THIRUMALA', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Australian Anzac', 'Lovely Bake Studio', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chocobakes Choc Filled Cookies', 'Cadbury', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coconut Milk Yogurt - Unsweetened, Dairy Free', 'Epigamia ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Irish Drink Shot', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Baked Pita Bread Crisps - Chilli & Garlic', 'Wingreens Farms', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Muffin/Cup Cake Blueberry 200 g + Choco Chip 200 g (Pack of 4 each)', 'Fresho Signature', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gluten - Free Chocolate Cake', 'The Baker''s Dozen', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Paneer', 'Nandini', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mozzarella Cheese - Diced', 'Go ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Danish - Cheese Pineapple', 'Fresho Signature', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Skimmed Milk', 'Nandini', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cake - Dates Walnut, Whole Wheat Eggless', 'BHealthy', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Paneer - Chilli', 'Soyfit', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Processed - Cheese', 'Gowardhan', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pizza Cheese - Mozzarella & Cheddar', 'Go ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bread - Fruit', 'English Oven', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Flavoured Milk - Chocolate', 'Heritage', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Soy Milk - Unsweetened', 'So Good', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Banana Milk Shake', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pizza Base - Whole Wheat, Safe, Preservative Free', 'Fresho', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Curd - Set', 'Milky Mist', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sterilised Double Toned Flavored Milk - Strawberry', 'THIRUMALA', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Croissants - Cheese', 'Fresho Signature', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Kool Cafe - Milk & Coffee', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies N Cream Gold Ice Cream', 'Amul', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Almond Coconut - Unsweetened Milk', 'So Good', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Garlic Cheese', 'Happy Milk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Malai Paneer - Organic', 'Akshayakalpa', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cashew & Oat Mylk', 'Goodmylk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Probiotic Yogurt - Vanilla Bean', 'Epigamia ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Grand''Or Dark & Hazelnuts', 'Heidi', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Crunch n Cream - Vanilla Cream Wafers', 'Tiffany', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ice Cream - Chocolate Almond, Stick', 'London Dairy', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chocolate Crackers - Crunchy, Family Pack', 'Malkist', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cheese Popcorn - Sour Cream & Wasabi', '4700BC', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tea - Cup of Life', 'Chymey', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Deluxe Crackers - Cheese', 'Kerk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('All Natural Peanut Butter - Unsweetened, Crunchy', 'Pintola', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Darjeeling Oolong Tea - Tapas', 'Teamonk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ramen Noodles - Hot Chicken Flavour, 2X Spicy', 'Samyang', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Java - Single Origin Milk Chocolate', 'Toska Chocolates', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sauce - Teriyaki', 'Ongs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Spanish Olives - Whole Green', 'Fragata', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fennel Blossom Honey', 'Sakurafresh', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rice Stick - 3 mm', 'Real Thai', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Bombay Cutting Chai Premium Chai Tea', 'TGL Co.', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Walker Ginger Stem Biscuit 150G', 'Walkers', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Variety Protein Bars Cranberry Orange-Kesar Almond Fudge-Coconut', 'GoodDiet', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Strawberry Ice Cream', 'Haagen-Dazs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Super Seeds Mix - Roasted Flax, Chia, Sesame, Sunflower, Watermelon, Pumpkin Seeds', 'Nutty Gritties', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dates Roll - Sugarfree, Oil Free', 'BHealthy', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Kantan Tennis Balls', 'Fini', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Masala Poori Atta', 'Graminway', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Assorted Mocha Instant Coffee - Strong, Double Chocolate, Mint, Blueberry', 'Colombian Brew Coffee', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fluffy Marshmallow - Vegetarian', 'marshmallow', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Olives Whole - Black', 'American Garden ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Thousand Island Dressing Lite', 'American Garden ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Barbeque Mayo', 'Wingreens Farms', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Burger - Chips', 'Neo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Olive Oil - Classic', 'La Espanola', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tangy Peanuts - Tomato', 'Roasty Tasty', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rice Crunchers - Wasabi', 'The Harvest Bowl', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Amla Dry Fruit', 'Fresho Signature', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Turmeric Cardamom Green Tea', 'Chaayos', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Vegan Chocolate Ice Cream', 'Papacream', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rosemary', 'On1y', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Flavouring Essence - Almond', 'Harveys', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Juice Drink With Nata De Coco - Mango', 'Dolphin ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gouda - Smoked', 'Kodai Cheese', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Greek Yogurt - Blueberry', 'Epigamia ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Almonds/Badam', 'Earthon', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Snacks - Super Rings, Cheese Flavoured', 'Oriental', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Roasted & Salted - Pumpkin Seed', 'Delight Nuts', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coffee Roasters - Medium-Dark Attikan Estate, Channi', 'Blue Tokai ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pepperolio Extra Virgin Olive Oil', 'Colavita', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fruit & Nut Chocolate', 'Toblerone', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Nutrione - Baked Cocktail Nuts', 'Tong Garden', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sauce - Taco (Hot)', 'Tex Mex Salsalito', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cocoa Powder', 'Hersheys ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Kashmiri Red Chilly Powder', 'Urban Platter', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Homemade  Seedless Amla Pickle - No Preservatives', 'Vaada', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Moorkulu', 'Haldirams ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Andhra Special Avakaya/Mango Pickle', 'Delight Foods', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Quinoa Muesli - Chocolate & Banana', 'Nourish You', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ocean Fresh - Seerfish Prime Steaks (Individually Frozen)', 'sumeru', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('BBQ Chicken Pizza - Large', 'HappyChef', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Sausages', 'sumeru', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Biscuit - Spicy', 'Bisk Farm', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mixed Fruit Jam', 'Kissan', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Popcorn - Classic Salted', 'ACT II', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Taco Shells', 'Dip', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Namkeen - Chatpata Dal', 'Haldirams ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('K Energy Bar - 55% Nuts & Grains - Choco Nutty', 'Kelloggs', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('5 Star - 3D Chocolate Bar', 'Cadbury', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gluten Free Salti', 'Schar', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Lime (South Indian Style)', 'Mother''s Recipe', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rainbow Sugar Balls', 'Ask Foods', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Coconut Peanut Butter - Smooth, Gluten Free, Non-GMO, Vegan', 'Alpino', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Honey Mustard Dressing', 'Veeba', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Roasted Jowar Puffs - Cheddar Cheese', 'The Healthy Cravings Co.', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Papad - Aloo', 'Saravanas', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Papad - Rice', 'Iyers ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Breakfast Cereal - Choco+, 3 Great Grains', 'Bagrrys', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Jelly Orange', 'Weikfield', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dark Fantasy Yumfills Pie', 'Sunfeast', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Custard Powder - Pineapple', 'Blue Bird', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pure Honey With Cinnamon - Green Tea & Lemon', 'Zandu', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Wasabi', 'Kari Kari', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Frozen Vegetables - Parwal', 'Farmland', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mysore Pak', 'Sangam Sweets', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Protein Rich Nutrition Bar - Berry Blast', 'Fit  ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Good Day Butter Cookies', 'Britannia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Crystals - Citric Acid', 'Eagle', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lemon Pepper Peanuts', 'Avean', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Icing Sugar', 'HappyChef', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Crispy Murukku', 'Garden', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sugar Free Cereals - Whole Oatmeal With Rolled Oats, Chia & Real Fruits', 'True Elements', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Assorted Pack', 'Unibic', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Popped Potato Chips - Cream Onion Divin', 'Tagz', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Natural Peanut Butter Crunch - Unsweetened/Gluten Free/ Non-GMO/Vegan', 'Alpino', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Papad - Garlic Disco', 'Atish ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rich Cocoa Dark Chocolate Bar', 'Cadbury Bournville', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Breakfast Mix - Foxtail Millet Dosa', 'GoodDiet', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Heat to Eat - Spicy Vegetable Biryani', 'TATA Q', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Marie Light - Oats Fibre Biscuits', 'Sunfeast', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Smiles Crispy - Happy Potatoes', 'McCain', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Thokku - Vathakozhambu', 'Grand Sweets', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Masala French Fries - Piri Piri', 'sumeru', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Natural Almond Butter - Unsweetened', 'Veeba', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Secret Manchurian Instant Noodles', 'Chings', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Veg. Burger Patty', 'Yummiez', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Khatha Meetha Nimbu', 'Graminway', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Eclairs Plus - Choco Caramel Chews', 'Chocoliebe', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Breakfast Mix - Oats Pongal', 'GoodDiet', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hing Jeera Peanuts', 'Avean', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ready to Fry - 3D Potato Long Square Tube', 'Tasties', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Granola - Choco, Almond & Cookies', 'Fit & Flex', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Potato Chips', 'Pringles', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Schezwan Instant Noodles + Tomato Instant Soup', 'Ching''S Secret', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Papad - Sabudana', 'Mother''s Recipe', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chicken Burger Patty', 'Elicious ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dried Fruit Cereal - Pineapple, Strawberry & Apricot', 'Munchilicious Granola ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Munch Chocolate Coated Crunchy Wafer - Share Pack', 'Nestle ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Peanut Butter - Jaggery Crunchy, No Preservatives', 'Happy Jars', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('O''Rice Cracker - Light & Tasty, Baked Not Fried', 'Orion', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Lollygum', 'Dukes', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mad Angles - Masala Madness', 'Bingo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Noodles - Saucy Masala', 'Sunfeast YiPPee!', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rasogolla', 'MTR', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Masala Upma Ready Mix', 'Organic Tattva', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ready Mix - Bajji Bonda', 'Grb', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sauce - Dark Soy 200G+Green Chilly 190G+Red Chilli 200G+Hakka Noodles Veg 150Gx2', 'Chings', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ready To Eat - Palak Paneer', 'MTR', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Toffee - Kismi', 'Parle', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tapioca Chips - Classic Salt', 'A-1 Chips', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dairy Milk - Silk Miniatures Collection', 'Cadbury Silk', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Whole Almond Bar', 'Hersheys ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('NutriChoice Oats Cookies - Orange Almond', 'Britannia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Poha Rice Flakes', 'SACHAMOTI', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('RTE BUTTER POPCORN PP', 'ACT II', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Breakfast Mix - Kodo Millet Rava Dosa', 'GoodDiet', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Potato Chips Original Style - Salt Sprinkled', 'Bingo', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pista Essence', 'HappyChef', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Milano Centre Filled Dark Cookies - Choco Delight', 'Parle', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Namkeen - Bhujia Sev', 'Haldirams ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Custard Powder - Strawberry', 'Weikfield', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cup Noodles Mazedaar Masala', 'Nissin Food', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Organic Green Chilly (Pure Mustard Oil & Spices)', 'Organic Nation', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Energy Bars - Nutty, 4+ Years, 100% Natural & Healthy', 'Timios', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Mango Sliced', 'MTR', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Schezwan Chutney', 'Madhur', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Icing Sugar', 'Weikfield', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Fantastik Mini Treats Chocolate Stick Wafer', 'Candyman', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Masala Oats - Peppy Tomato', 'Saffola', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Multigrain Diet Muesli', 'True Elements', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Falooda Mix Rose', 'Weikfield', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Original - Ready To Fry Mini Rice Papad, Cumin', 'Fryums', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('NutriChoice Digestive High Fibre Biscuits - Family Pack', 'Britannia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dried Oranges', 'FabBox', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ginger Honey', 'Graminway', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Jalapeno Pasta Sauce 385 g + Sriracha Chilli Sauce 185 g + Hot Sauce 75 ml', 'Habanero', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Jelly Strawberry', 'Weikfield', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Natural Blossom Honey', 'Hamdard', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Energy Bars - Nutty, 4+ Years, 100% Natural & Healthy', 'Timios', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ready To Cook - Quinoa Kara Pongal', 'Prasukh', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Milk', 'Unibic', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Four Cheese Thin Pizza', 'Iceland', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Namkeen - Cornflakes Masala', 'Sln  ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Premium Wafer Bites - Dark Choco', 'Tasties', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Oatmeal (Sugar Free)', 'Unibic', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Paneer Pan', 'Bon curry ', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Rolled Oats - Gluten Free + Gluten Free - Steel Cut Oats (each 500 g)', 'True Elements', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sriracha Sauce', 'Spice Story', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Juzt Jelly - Strawberry Flavour', 'ALPENLIEBE', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Milk Cookies', 'Micks', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Chicken', 'Double Horse', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Instant - Khara Bhath Mix', 'Sanketi Adukale', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Garlic', 'Double Horse', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Mexican Chicken Pizza', 'Iceland', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Potato Chips', 'Pringles', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('FunFoods Eggless Bake Mix 11 Cakes', 'Dr. Oetker', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Daily Treat - Navaratan Korma', 'Kitchens Of India', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gems - Sugar Coated Chocolate', 'Cadbury', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hide & Seek - Black Bourbon Vanilla', 'Parle', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Gulab Jamun - Gol M Gol', 'Bikaji', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Treat Stars - Creme & Milk Choco Duo Cream Biscuits', 'Britannia', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Butter Cashew Cookies', 'Tasties', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ready to Cook & Serve - Cheese Onion Pockets', 'Amul Happy Treats', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Biscuits - So Sweet', 'Bisk Farm', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Puff - Pastry Sheet', 'Unroll', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dharwad Peda', 'Sangam Sweets', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Desiccated Coconut', 'Coco mama', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Tandoori Chicken Tikka Pizza - Large', 'HappyChef', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cranberry Dark Chocolate Bar', 'Cadbury Bournville', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Hot Garlic Stir Fry Sauce & Dip', 'Veeba', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Instant Popcorn - Butter Pepper', 'ACT II', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Makhana - Roasted, Tomato', 'PRAVIN MIXBOX', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Rice Mix - Tamarind', 'Aaha Oho', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Dry Gol Gappa/Pani Puris - Ready-To-Fry', 'Urban Platter', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('French - Fries', 'McCain', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Pickle - Mango', 'Mother''s Recipe', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Namkeen - Cocktail Nuts', 'Jabsons', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Sweetss - Badam halwa', 'Sangam Sweets', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Chunky Shawarma Chicken', 'Licious', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Synthetic Food Colour Preparation Apple Green', '999', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Khatt-Mith Organic Tomato Ketchup - Dipping & Cooking Sauce, Sugar-Free', 'D-Alive', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cheese Cracker', 'Mcvities', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Ragi Dosa Mix', 'Grami Superfoods', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Cookies - Daily Digestive Oatmeal', 'Unibic', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Organic Peanut Butter Smooth - Unsweetened/Gluten Free/ Non-GMO/Vegan', 'Alpino', 'Packaged', 'each');
INSERT INTO product (Name, Brand, Category, Sale_Unit) VALUES ('Water', 'Generic', 'Commodity', 'Liter');

-- needsComponent Table Inserts (Specific Rules with Float Quantities) --
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (26, 601, 1.71);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (15, 601, 1.3);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (42, 601, 1.4);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (43, 601, 1.41);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (33, 601, 1.88);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (34, 601, 0.58);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (10, 601, 1.17);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (38, 601, 0.12);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (24, 601, 0.53);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (31, 601, 1.08);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (494, 101, 1.73);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (494, 149, 0.64);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (598, 246, 0.1);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (598, 205, 0.3);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (598, 111, 0.56);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (552, 116, 0.48);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (552, 156, 1.33);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (552, 203, 1.19);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (454, 175, 1.55);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (454, 214, 1.52);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (454, 180, 1.1);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (454, 205, 0.54);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (559, 190, 1.22);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (559, 111, 0.25);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (559, 250, 0.75);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (520, 126, 0.58);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (537, 165, 0.68);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (537, 119, 1.21);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (478, 231, 0.62);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (478, 235, 0.9);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (478, 210, 1.54);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (478, 140, 1.19);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (497, 103, 0.17);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (508, 113, 0.28);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (508, 103, 0.77);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (467, 138, 0.28);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (467, 190, 0.42);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (488, 168, 0.28);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (488, 238, 1.6);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (488, 137, 0.83);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (488, 124, 1.93);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (468, 112, 1.9);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (501, 110, 0.6);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (501, 229, 1.86);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (501, 135, 1.13);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (501, 170, 0.32);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (591, 143, 1.89);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (591, 163, 1.46);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (591, 189, 0.71);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (591, 110, 1.52);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (599, 245, 0.69);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (593, 151, 1.05);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (593, 123, 1.28);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (593, 147, 1.58);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (453, 112, 1.15);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (498, 118, 1.34);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (498, 243, 1.68);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (498, 197, 0.35);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (498, 221, 0.99);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (458, 227, 1.45);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (458, 213, 0.8);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (458, 141, 1.6);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (458, 150, 1.63);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (499, 139, 0.96);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (499, 190, 1.72);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (499, 119, 1.42);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (499, 150, 1.45);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (514, 192, 1.0);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (514, 212, 0.83);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (514, 187, 1.66);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (566, 129, 1.49);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (566, 233, 0.27);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (566, 199, 0.4);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (566, 206, 1.8);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (519, 207, 1.72);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (519, 235, 0.36);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (462, 111, 1.52);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (462, 212, 1.61);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (492, 196, 1.23);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (492, 238, 1.56);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (492, 159, 1.08);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (492, 139, 0.52);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (527, 110, 1.55);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (509, 200, 1.87);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (509, 163, 0.86);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (509, 126, 1.69);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (464, 172, 0.96);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (464, 188, 0.77);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (464, 221, 0.44);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (594, 230, 1.54);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (594, 249, 0.23);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (594, 172, 0.68);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (460, 102, 1.02);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (460, 163, 1.99);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (460, 174, 0.52);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (485, 170, 1.43);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (457, 207, 1.82);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (457, 117, 1.29);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (457, 148, 1.48);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (457, 114, 0.88);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (569, 151, 0.31);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (569, 131, 1.71);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (555, 174, 0.57);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (555, 168, 0.13);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (590, 244, 1.1);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (590, 191, 0.97);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (590, 140, 0.23);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (590, 242, 0.17);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (461, 223, 0.42);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (461, 180, 0.53);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (475, 187, 1.82);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (475, 180, 1.82);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (518, 114, 0.14);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (466, 119, 0.23);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (466, 190, 1.57);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (576, 163, 0.76);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (576, 135, 0.98);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (576, 160, 0.19);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (576, 177, 1.21);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (480, 206, 1.58);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (480, 178, 1.01);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (480, 187, 0.73);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (484, 233, 1.86);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (484, 238, 0.11);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (582, 116, 1.09);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (582, 192, 0.95);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (582, 191, 1.88);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (595, 129, 1.08);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (595, 235, 1.28);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (490, 197, 0.27);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (567, 181, 1.11);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (567, 157, 1.17);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (567, 244, 1.6);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (567, 219, 1.68);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (503, 176, 0.7);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (493, 131, 0.34);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (493, 171, 0.48);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (493, 162, 1.97);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (493, 134, 1.6);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (533, 197, 1.72);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (533, 151, 0.35);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (533, 191, 1.52);
INSERT INTO needsComponent (Parent_PID, Child_PID, Quantity_Needed) VALUES (533, 130, 1.71);

commit;